//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAP.Appointments.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int IdKey { get; set; }
        public int IdKeyPacient { get; set; }
        public System.DateTime Date { get; set; }
        public int IdType { get; set; }
        public int IdState { get; set; }
    
        public virtual Pacient Pacient { get; set; }
        public virtual State State { get; set; }
        public virtual Type Type { get; set; }
    }
}
